# permissions for end users to view physicaldevices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: anankix
    app.kubernetes.io/managed-by: kustomize
  name: physicaldevice-viewer-role
rules:
- apiGroups:
  - device.anankix.io
  resources:
  - physicaldevices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - device.anankix.io
  resources:
  - physicaldevices/status
  verbs:
  - get
